#Choice service selector: possible values are
# - "markov" for Markov Chain based logic
# - "random" for pure random based logic
choice.service: markov

logging:
  level:
    root: INFO
    com.acme.games: DEBUG
